-- UEW2PRO_PT.CM_LAYER2 definition

CREATE TABLE "CM_LAYER2" 
   (	"LAYERID" NUMBER NOT NULL ENABLE, 
	"PARENTLAYERID" NUMBER, 
	"LAYERNAME" VARCHAR2(50), 
	"TABLENAME" VARCHAR2(30), 
	"THEMATICSTYLE" VARCHAR2(20), 
	"THEMATICKEY" VARCHAR2(20), 
	"THEMATICVALUE1" VARCHAR2(20), 
	"THEMATICVALUE2" VARCHAR2(20), 
	"LINESTYLE" VARCHAR2(20), 
	"LINECOLORA" VARCHAR2(3), 
	"LINECOLORR" VARCHAR2(3), 
	"LINECOLORG" VARCHAR2(3), 
	"LINECOLORB" VARCHAR2(3), 
	"LINEWIDTH" VARCHAR2(20), 
	"FILLCOLORA" VARCHAR2(20), 
	"FILLCOLORR" VARCHAR2(20), 
	"FILLCOLORG" VARCHAR2(20), 
	"FILLCOLORB" VARCHAR2(20), 
	"FONTFAMILY" VARCHAR2(30), 
	"FONTOUTLINECOLORA" VARCHAR2(3), 
	"FONTOUTLINECOLORR" VARCHAR2(3), 
	"FONTOUTLINECOLORG" VARCHAR2(3), 
	"FONTOUTLINECOLORB" VARCHAR2(3), 
	"FONTOUTLINEWIDTH" VARCHAR2(20), 
	"FONTOUTLINEJOIN" VARCHAR2(20), 
	"FONTOUTLINEMITERLIMIT" VARCHAR2(20), 
	"FONTFILLCOLORA" VARCHAR2(3), 
	"FONTFILLCOLORR" VARCHAR2(3), 
	"FONTFILLCOLORG" VARCHAR2(3), 
	"FONTFILLCOLORB" VARCHAR2(3), 
	"FONTTEXTALIGN" VARCHAR2(20), 
	"FONTVERTICALALIGN" VARCHAR2(20), 
	"SYMBOLNAME" VARCHAR2(30), 
	"SELECTABLE" VARCHAR2(1), 
	"EDITABLE" VARCHAR2(1), 
	"VISIBLE" VARCHAR2(1), 
	"LABELVISIBLE" VARCHAR2(1), 
	"LAYERTP" VARCHAR2(10), 
	"LAYERPOINTDETAILTP" CHAR(5), 
	"LAYERSEQ" NUMBER NOT NULL ENABLE, 
	"USE_YN" VARCHAR2(1), 
	"ISLAYER" VARCHAR2(1), 
	"CQLFILTER" VARCHAR2(2000), 
	"LABELCOLUMN" VARCHAR2(20), 
	"MINZOOM" NUMBER, 
	"FRST_REGISTER_DATE" DATE, 
	"LAST_UPDATE_DATE" DATE, 
	"FULLNAME" VARCHAR2(200), 
	"DOWNLOAD_YN" VARCHAR2(1), 
	 PRIMARY KEY ("LAYERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TS_UNIEMWATER_DAT01"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "TS_UNIEMWATER_DAT01" ;

CREATE UNIQUE INDEX "SYS_C00266621" ON "CM_LAYER2" ("LAYERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TS_UNIEMWATER_DAT01" ;

COMMENT ON TABLE UEW2PRO_PT.CM_LAYER2 IS 'GIS레이어';
COMMENT ON COLUMN UEW2PRO_PT.CM_LAYER2.THEMATICVALUE1 IS '매틱값1';
COMMENT ON COLUMN UEW2PRO_PT.CM_LAYER2.LINECOLORB IS '라인색상 (B)';
COMMENT ON COLUMN UEW2PRO_PT.CM_LAYER2.FONTOUTLINEMITERLIMIT IS '폰트외곽선 미터한계';
COMMENT ON COLUMN UEW2PRO_PT.CM_LAYER2.FONTFILLCOLORG IS '폰트색상 (G)';
COMMENT ON COLUMN UEW2PRO_PT.CM_LAYER2.FONTTEXTALIGN IS '텍스트 정렬(수평)';
COMMENT ON COLUMN UEW2PRO_PT.CM_LAYER2.LAYERSEQ IS '레이어 순번';
COMMENT ON COLUMN UEW2PRO_PT.CM_LAYER2.LAST_UPDATE_DATE IS '수정일';
COMMENT ON COLUMN UEW2PRO_PT.CM_LAYER2.DOWNLOAD_YN IS 'SHP 다운로드 가능여부';