var searchHtmlArray ={
	/**
	 * ======================================================================================================
	 * point 
	 * ======================================================================================================
	 */
	WTL_FLOW_PS :{
		GAG_CDE:"유량계용도|select|MOC_CC_025",
		MOF_CDE:"유량계형식|select|MOC_CC_026",
		FLO_NM:"유량계명|text",
		FLO_DIP:"구경|text",
		IST_YMD:"설치일자|text",
		LFTRIDN:"대블록|select|blbgAs",
		MFTRIDN:"중블록|select|blbmAs",
		SFTRIDN:"소블록|select|blsmAs",
	},
	WTL_PRGA_PS :{
		PGA_CDE:"수압계형식|select|MOC_CC_021",
		MOF_CDE:"수압계용도|select|MOC_CC_022",
		PRG_NM:"블록명|text",
		PGA_DIP:"구경|text",
		IST_YMD:"설치일자|text",
		LFTRIDN:"대블록|select|blbgAs",
		MFTRIDN:"중블록|select|blbmAs",
		SFTRIDN:"소블록|select|blsmAs",
	},
	WTL_META_PS :{
		DMNO:"수용가번호|text",
		MET_MOF:"계량기형식|select|MOC_CC_022",
		MET_NUM:"기물번호|text",
		MET_DIP:"계량기구경|text",
		IST_YMD:"설치일자|text",
		LFTRIDN:"대블록|select|blbgAs",
		MFTRIDN:"중블록|select|blbmAs",
		SFTRIDN:"소블록|select|blsmAs",
	},
	WTL_VALV_PS :{
		FTR_CDE:"지물부호|select|MOC_CC_031",
		VAL_MOF:"밸브형식|select|MOC_CC_022",
		VAL_MOP:"밸브재질|select|OGC-030",
		OFF_CDE:"개폐여부|select|MOC_CC_009",
		PIP_IDN:"상수관번호|text",
		VAL_DIP:"구경|text",
		IST_YMD:"설치일자|text",
		LFTRIDN:"대블록|select|blbgAs",
		MFTRIDN:"중블록|select|blbmAs",
		SFTRIDN:"소블록|select|blsmAs",
	},
	WTL_FIRE_PS :{
		IST_YMD:"설치일자|text",
		DMNO:"수용가번호|text",
		MOF_CDE:"소화전형식|select|MOC_CC_019",
		FIR_DIP:"소화전구경|text",
		PIP_DIP:"배수관구경|text",
		SUP_HIT:"급수탑높이|text",
		ANG_DIR:"방향각|text",
		CNT_NUM:"공사번호|text",
		LFTRIDN:"대블록|select|blbgAs",
		MFTRIDN:"중블록|select|blbmAs",
		SFTRIDN:"소블록|select|blsmAs",
	},
	/**
	 * ======================================================================================================
	 * line 
	 * ======================================================================================================
	 */
	WTL_PIPE_LS :{
		MOP_CDE:"관재질|select|MOC_CC_003",
		SAA_CDE:"상수관용도|select|MOC_CC_014",
		JHT_CDE:"접합종류|select|MOC_CC_015",
		PIP_DIP:"배수관구경|text",
		IST_YMD:"설치일자|text",
		LFTRIDN:"대블록|select|blbgAs",
		MFTRIDN:"중블록|select|blbmAs",
		SFTRIDN:"소블록|select|blsmAs",
	},
	WTL_SPLY_LS :{
		MOP_CDE:"관재질|select|MOC_CC_003",
		SAA_CDE:"상수관용도|select|MOC_CC_014",
		JHT_CDE:"접합종류|select|MOC_CC_015",
		PIP_DIP:"배수관구경|text",
		IST_YMD:"설치일자|text",
		LFTRIDN:"대블록|select|blbgAs",
		MFTRIDN:"중블록|select|blbmAs",
		SFTRIDN:"소블록|select|blsmAs",
	},
	
	/**
	 * ======================================================================================================
	 * area 
	 * ======================================================================================================
	 */
	WTL_BLBG_AS :{
		BLK_NAM:"블록명|text",
		WSP_NAM:"급수계통명|text",
		WSP_BIG:"최대급수량|text",
		PPL_NUM:"인구|text",
		GNR_NUM:"세대수|text",
	},
	WTL_BLBM_AS :{
		BLK_NAM:"블록명|text",
		WSP_NAM:"급수계통명|text",
		UBL_IDN:"대블록번호|text",
		PPL_NUM:"인구|text",
		UPD_DTM:"변경일시|text|",
	},
	WTL_BLSM_AS :{
		BLK_NAM:"블록명|text",
		WSP_NAM:"급수계통명|text",
		UBL_IDN:"중블록번호|text",
	},
	//취수장
	WTL_GAIN_AS :{
		GAI_NAM:"취수장명|text",
		WSR_CDE:"수원구분|select|OGC-138",
		WRW_CDE:"도수방법|select|OGC-130",
		WGW_CDE:"취수방법|select|OGC-143",
		WSS_NAM:"수계명|text",
		HGA_VOL:"시설용량|text",
		PMP_CNT:"펌프대수|text",
		PMP_VOL:"펌프용량|text",
		GAI_ARA:"부지면적|text",
		FNS_YMD:"준공일자|text",
		LFTRIDN:"대블록|select|blbgAs",
		MFTRIDN:"중블록|select|blbmAs",
		SFTRIDN:"소블록|select|blsmAs",
	},
	//정수장
	WTL_PURI_PS :{
		PUR_NAM:"정수장명|text",
		WSR_CDE:"수원구분|select|MOC_CC_023",
		SAM_CDE:"여과방법|select|MOC_CC_029",
		GAI_NAM:"관련취수장|text",
		SRV_NAM:"관련배수지|text",
		PUR_VOL:"시설용량|text",
		PWR_VOL:"계약전력|text",
		PUR_ARA:"부지면적|text",
		FNS_YMD:"준공일자|text",
		LFTRIDN:"대블록|select|blbgAs",
		MFTRIDN:"중블록|select|blbmAs",
		SFTRIDN:"소블록|select|blsmAs",
	},
	//배수지
	WTL_SERV_PS :{
		SRV_NAM:"배수지명|text",
		PUR_NAM:"관련정수장|text",
		SUP_ARE:"급수지역|text",
		SAG_CDE:"관리방법|select|MOC_CC_006",
		SCW_CDE:"제어방법|select|MOC_CC_007",
		SRV_ARA:"부지면적|text",
		SRV_VOL:"시설용량|text",
		SRV_ALT:"배수지표고|text",
		ISR_VOL:"유입량|text",
		UPD_DTM:"변경일시|text|",
		LFTRIDN:"대블록|select|blbgAs",
		MFTRIDN:"중블록|select|blbmAs",
		SFTRIDN:"소블록|select|blsmAs",
	},
	//가압장
	WTL_PRES_PS :{
		PRS_NAM:"가압장명|text",
		PRS_ARA:"부지면적|text",
		SAG_CDE:"관리방법|select|MOC_CC_001",
		PRS_ALT:"가압장표고|text",
		PRS_VOL:"시설용량|text",
		FNS_YMD:"준공일자|text",
		LFTRIDN:"대블록|select|blbgAs",
		MFTRIDN:"중블록|select|blbmAs",
		SFTRIDN:"소블록|select|blsmAs",
	},
	WTL_VALB_AS :{
		SGCCD:"지자체코드|hidden",
		FTR_CDE:"지물부호|text|",
		FTR_IDN:"관리번호|text|",
		HJD_CDE:"행정구역|text",
		MNG_CDE:"관리기관|text",
		IST_YMD:"설치일자|text",
		MAN_STD:"규격|text",
		SOM_CDE:"밸브실용도|text",
		MAN_CNT:"맨홀뚜껑수|text",
		MHS_STD:"맨홀규격|text",
		UTG_LOC:"매설환경|text",
		KEY_CNT:"키홀수량|text",
		KEY_STD:"키홀규격|text",
		MAN_MOP:"구조물재질|text",
		MHS_CDE:"맨홀형태|text",
		CNT_NUM:"공사번호|text",
		SYS_CHK:"대장초기화|text",
		PIP_CDE:"상수관부호|text",
		PIP_IDN:"상수관번호|text",
		BSM_CDE:"블록부호|text",
		BSM_IDN:"블록번호|text",
		WID_CDE:"광역구분|text",
		UPD_DTM:"변경일시|text|",
		SHAPE_LENG:"모형길이|text",
		SHAPE_AREA:"모형영역|text",
		FTR_IDS:"지물번호|hidden",
	}
}
